#!/usr/bin/env bash
set -e
git config --global http.postBuffer 157286400
git config --global core.compression 0
git -C /opt clone https://github.com/redpanda-data/kafka-streams-examples.git --branch ducktape-debug
cd /opt/kafka-streams-examples
git reset --hard 913d08c8351c74ee454b79f8e0c1f48ca9b562a5
mvn -DskipTests=true clean package
