#!/usr/bin/env bash
set -e
# ref: https://goteleport.com/docs/installation/#one-line-installation-script
TELEPORT_EDITION="oss"
TELEPORT_VERSION="15.3.1"
curl https://goteleport.com/static/install.sh | bash -s ${TELEPORT_VERSION?} ${TELEPORT_EDITION?}